name: unpack

on:
  workflow_dispatch:
     inputs:
       mode:
         description: 'Download mode(aria2c,curl,axel,wget)'
         required: true
         default: 'aria2c'
       output:
         description: 'Output(wget=O)'
         required: true
         default: 'o'
       filelink:
         description: 'Boot Link'
         required: true
       artifact:
         description: 'Upload to Artifact'
         required: true
         default: 'true'

jobs:
  unpack:
    runs-on: ubuntu-20.04
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git openjdk-8-jdk wget curl rsync aria2 python python3 unzip device-tree-compiler brotli simg2img img2simg axel
          pip3 install protobuf
          pip install brotli

      - id: var
        name: Download
        run: |
          echo "Download"
          ${{ github.event.inputs.mode }} ${{ github.event.inputs.filelink }} -${{ github.event.inputs.output }} "boot.img"
          ls -al

      - name: ramdisk.cpio Extracting
        run: |
          mkdir tmp
          cp boot.img tmp
          cd tmp
          ../magiskboot unpack -h boot.img
          cp ramdisk.cpio ../output/
          ls
          cpio -i -F ramdisk.cpio
          ls -R
          cd ..

      - name: img_info && dts Extracting
        run: |
          echo "Patching boot"
          mv boot.img mkbootimg
          cd mkbootimg
          ./mkboot boot.img boot
          rm boot.img
          cd boot
          ls -al
          echo "打印出boot下所有文件"
          echo "**************************************"
          mv kernel image.gz-dtb
          ../../split-appended-dtb image.gz-dtb
          rm image.gz-dtb
          ls
          for i in `find *.dtb`
          do
            if [[ ! -z "$(../../fdtget $i /firmware/android/fstab -p 2>/dev/null || true)" ]]; then
                echo "**************************************"
                ../../magiskboot dtb $i print -f
                echo "**************************************"
                ../../fdtget $i /firmware/android/vbmeta parts 2>/dev/null || true
                ../../fdtput $i -r /firmware/android/vbmeta
                echo "**************************************"
                if [[ ! -z "$(../../fdtget $i /firmware/android/fstab/system -p 2>/dev/null || true)" ]]; then
                ../../fdtput $i /firmware/android/fstab/vendor dev /dev/block/platform/soc/7824900.sdhci/by-name/vendor -ts
                ../../fdtput $i /firmware/android/fstab/vendor status disable -ts
                echo "列出android下的节点"
                ../../fdtget $i /firmware/android/vbmeta -l 2>/dev/null || true
                ../../fdtget $i /firmware/android/vbmeta parts 2>/dev/null || true
                echo "**************************************"
                ../../magiskboot dtb $i print -f
                echo "**************************************"
                dtb=${i##* }
                dts=${dtb%.*}.dts
                echo "dtb $dtb"
                echo "dts $dts"
                ../../dtc -q -I dtb -O dts -o $dts $dtb
                line="$(grep -n "firmware {" $dts)"
                linea="$(echo $line | cut -d ":" -f 1)"
                line="$(grep -n "reserved-memory" $dts)"
                lineb="$(echo $line | cut -d ":" -f 1)"
                lineb="`expr $lineb - 1`""p"
                echo "**************************************"
                sed -n "$linea,$lineb" $dts
                echo "**************************************"
                mv $dts ../../output/$dts
            fi
          done
          echo "**************************************"
          ls -al
          echo "**************************************"
          cat kernel *.dtb > image.gz-dtb
          rm -f *.dtb
          rm -f kernel
          mv image.gz-dtb kernel
          echo "列出所有文件"
          echo "**************************************"
          cd ..
          ./mkboot boot boot.img
          cp boot.img ../../output
          ls -al

      - name: dtbo.img Extracting
        continue-on-error: true
        run: |
          echo "mkdting"
          if [[ -f "dtbo.img" ]]; then
              cp dtbo.img dtbo2dts/
              cd dtbo2dts
              python dtbo2dtsi.py
              rm dtbo.img
              ls -al
              line="$(grep -n "vbmeta" dtsi.0)"
              linea="$(echo $line | cut -d ":" -f 1)"
              lineb="`expr $linea + 24`""p"
              sed -n "$linea,$lineb" dtsi.*
              cp dtsi.* ../output/
              cd ../
          fi

      - name: Packing
        run: |
          echo "packing"
          cd output
          ls -al

      - name: Upload to Artifact
        if: github.event.inputs.artifact == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            output
          retention-days: 7
