name: unpack

on:
  workflow_dispatch:
     inputs:
       mode:
         description: 'Download mode(aria2c,curl,axel,wget)'
         required: true
         default: 'aria2c'
       output:
         description: 'Output(wget=O)'
         required: true
         default: 'o'
       filelink:
         description: 'Boot Link'
         required: true
       artifact:
         description: 'Upload to Artifact'
         required: true
         default: 'true'

jobs:
  unpack:
    runs-on: ubuntu-20.04
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git openjdk-8-jdk wget curl rsync aria2 python python3 unzip device-tree-compiler brotli simg2img img2simg axel
          pip3 install protobuf
          pip install brotli

      - id: var
        name: Download
        run: |
          echo "Download"
          ${{ github.event.inputs.mode }} ${{ github.event.inputs.filelink }} -${{ github.event.inputs.output }} "boot.img"
          mv boot.img output/boot.img
          ls -al

      - name: boot Patching
        run: |
          echo "Patching boot"
          mv output/boot.img mkbootimg/
          cd mkbootimg
          ./mkboot boot.img boot
          rm boot.img
          cd boot
          echo "打印出boot下所有文件"
          echo "**************************************"
          ls -al
          mv kernel image.gz-dtb
          ../../split-appended-dtb image.gz-dtb
          rm image.gz-dtb
          for i in `find *.dtb`; do
            if [[ ! -z "$(../../fdtget $i /firmware/android/fstab -p 2>/dev/null || true)" ]]; then
                echo "**************************************"
                ../../magiskboot dtb $i print -f
                echo "**************************************"
                ../../fdtput $i /firmware/android/fstab/vendor dev /dev/block/platform/soc/7824900.sdhci/by-name/vendor -ts
                ../../fdtput $i /firmware/android/fstab/vendor status disable -ts
                echo "**************************************"
                ../../magiskboot dtb $i print -f
                echo "**************************************"
                dtb=${i##* }
                dts=${dtb%.*}.dts
                echo "dtb $dtb"
                echo "dts $dts"
                ../../dtc -q -I dtb -O dts -o $dts $dtb
                line="$(grep -n "firmware {" $dts)"
                linea="$(echo $line | cut -d ":" -f 1)"
                line="$(grep -n "reserved-memory" $dts)"
                lineb="$(echo $line | cut -d ":" -f 1)"
                lineb="`expr $lineb - 1`""p"
                echo "**************************************"
                sed -n "$linea,$lineb" $dts
                echo "**************************************"
                mv $dts ../../output/$dts
            fi
          done
          echo "**************************************"
          ls -al
          echo "**************************************"
          cat kernel *.dtb > image.gz-dtb
          rm -f *.dtb
          rm -f kernel
          mv image.gz-dtb kernel
          echo "列出所有文件"
          echo "**************************************"
          ls -al
          echo "**************************************"
          cd ..
          ./mkboot boot boot.img
          mv boot.img ../output/boot.img
          cd ..

      - name: Packing
        run: |
          echo "packing"
          cd output
          ls -al

      - name: Upload to Artifact
        if: github.event.inputs.artifact == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            output
          retention-days: 7
